---

apiVersion: v1
kind: Secret
type: kubernetes.io/rbd
metadata:
  name: ceph-secret
  namespace: kube-system
data:
  key: {{ ceph_user_token }}

---

apiVersion: v1
kind: Secret
type: kubernetes.io/rbd
metadata:
  name: ceph-secret
  namespace: kube-public
data:
  key: {{ ceph_user_token }}

---

apiVersion: v1
kind: Secret
type: kubernetes.io/rbd
metadata:
  name: ceph-secret
  namespace: default
data:
  key: {{ ceph_user_token }}

{% for namespace in k8s_namespaces %}
---

apiVersion: v1
kind: Secret
type: kubernetes.io/rbd
metadata:
  name: ceph-secret
  namespace: {{ namespace }}
data:
  key: {{ ceph_user_token }}

{% endfor %}
