{% for namespace in k8s_namespaces %}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ namespace }}
  namespace: {{ namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ namespace }}-admin
subjects:
- kind: User
  name: {{ k8s_release_username }}

{% endfor %}