{% for namespace in k8s_namespaces %}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ namespace }}-admin
  namespace: {{ namespace }}
  labels:
    basic.auth/role: {{ namespace }}-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

{% endfor %}
