---
- name: Check addons directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_addons_dir }}'
    - '{{ k8s_kube_registry_dir }}'

- name: Kube registry
  template:
    src: "{{ item }}"
    dest: "{{ k8s_addons_dir }}/{{ item }}"
  with_items:
    - kube-registry.yaml

- name: Deploy script for kube registry
  template:
    src: deploy-registry.sh
    dest: "{{ k8s_addons_dir }}/deploy-registry.sh"
    mode: 0755

- name: Run deploy script for registry
  command: "{{ k8s_addons_dir }}/deploy-registry.sh"
  when: inventory_hostname in k8s_master_hosts[0]
