---

apiVersion: v1
kind: Secret
metadata:
  name: istio-ingress-certs
  namespace: {{ k8s_istio_namespace }} 
data:
  tls.crt: {{ k8s_services_cert | b64encode }}
  tls.key: {{ k8s_services_cert_key | b64encode }}
