---
- hosts:
    - master
    - node
    - build
    - master_lb
    - node_lb
    - gateway_lb
  remote_user: '{{ k8s_ssh_user }}'
  become: true

  roles:
    - role: logrotate
    - role: journald
