{% include 'scrape_configs/prometheus.yml' %}

{% include 'scrape_configs/kubernetes.yml' %}

{% if k8s_prometheus_scrape_istio_metrics %}
{% include 'scrape_configs/istio.yml' %}
{% endif %}

{% if k8s_prometheus_scrape_cockroachdb_metrics %}
{% include 'scrape_configs/cockroachdb.yml' %}
{% endif %}
