      # A scrape configuration for monitoring itself
      #
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090

      - job_name: 'prometheus-pushgateway'
        honor_labels: true

        kubernetes_sd_configs:
          - role: service

        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
            action: keep
            regex: pushgateway
