---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoheaders
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: {{ k8s_echoserver_image }}:{{ k8s_echoserver_image_tag }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10

---

apiVersion: v1
kind: Service
metadata:
  name: echoheaders
  labels:
    app: echoheaders
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: echoheaders
spec:
  tls:
  - hosts:
    - {{ k8s_services_name }}
    secretName: tls-secret
  rules:
  - host: {{ k8s_services_name }}
    http:
      paths:
      - path: /echo1
        backend:
          serviceName: echoheaders
          servicePort: 80
      - path: /echo2
        backend:
          serviceName: echoheaders
          servicePort: 80
