---
- name: Check addons directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_prometheus_dir }}'

- name: Prometheus
  template:
    src: "{{ item }}"
    dest: "{{ k8s_prometheus_dir }}/{{ item }}"
  with_items:
    - config.yaml
    - prometheus.yaml

- name: Deploy script for Prometheus
  template:
    src: deploy-prometheus.sh
    dest: "{{ k8s_prometheus_dir }}/deploy-prometheus.sh"
    mode: 0755

- name: Run deploy script for Prometheus
  command: "{{ k8s_prometheus_dir }}/deploy-prometheus.sh"
  when: inventory_hostname in k8s_master_hosts[0]
