---
# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_addons_dir: '{{ k8s_conf_dir }}/addons'

# Master hosts nsmes
k8s_master_hosts: {}

# Heapster images
k8s_heapster_image: gcr.io/google_containers/heapster-amd64
k8s_heapster_image_tag: v1.5.0
k8s_heapster_addon_resizer_image: gcr.io/google_containers/addon-resizer
k8s_heapster_addon_resizer_image_tag: 1.8.1
k8s_heapster_influxdb_image: gcr.io/google_containers/heapster-influxdb-amd64
k8s_heapster_influxdb_image_tag: v1.3.3
k8s_heapster_grafana_image: gcr.io/google_containers/heapster-grafana-amd64
k8s_heapster_grafana_image_tag: v4.4.3

# Heapster parameters
k8s_heapster_base_metrics_memory: "140Mi"
k8s_heapster_base_metrics_cpu: "80m"
k8s_heapster_base_eventer_memory: "190Mi"
k8s_heapster_metrics_memory_per_node: 4
k8s_heapster_metrics_cpu_per_node: 0.5
k8s_heapster_eventer_memory_per_node: 500
k8s_heapster_num_nodes: 3
k8s_heapster_nanny_memory_per_node: 200
k8s_heapster_nanny_memory: '{% if k8s_heapster_num_nodes >= 0 %} {{ (90 * 1024 + k8s_heapster_num_nodes * k8s_heapster_nanny_memory_per_node)|string + "Ki" }} {% else %} "90Mi" {% endif %}'
