---
# Kubernetes load balancer type, valid values: `gce`, `nginx`, `haproxy`
# TODO: load balancer `gce`, `haproxy`
k8s_lb_type: nginx 

# PROXY protocol for ingress
# https://www.haproxy.com/blog/haproxy/proxy-protocol/
k8s_ingress_proxy_protocol: false

# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_addons_dir: '{{ k8s_conf_dir }}/addons'

# Master hosts nsmes
k8s_master_hosts: {}

# Nodes hosts names
k8s_node_hosts: {}

# Nginx Ingress controller images
k8s_defaultbackend_image: gcr.io/google_containers/defaultbackend
k8s_defaultbackend_image_tag: 1.4
k8s_echoserver_image: gcr.io/google_containers/echoserver
k8s_echoserver_image_tag: 1.8
k8s_nginx_ingress_controller_image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
k8s_nginx_ingress_controller_image_tag: 0.9.0
