---
# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_addons_dir: '{{ k8s_conf_dir }}/addons'

# Master hosts names
k8s_master_hosts: {}

# Prometheus host names (for Prometheus, AlertManager, PushGateway, Grafana)
k8s_prometheus_name: ''
k8s_prometheus_alertmanager_name: ''
k8s_prometheus_pushgateway_name: ''
k8s_prometheus_grafana_name: ''

# Prometheus namespace
k8s_prometheus_namespace: default

# Prometheus images
k8s_prometheus_image: prom/prometheus
k8s_prometheus_image_tag: v1.7.2
k8s_prometheus_alertmanager_image: prom/alertmanager
k8s_prometheus_alertmanager_image_tag: v0.9.1
k8s_prometheus_ksm_image: gcr.io/google_containers/kube-state-metrics
k8s_prometheus_ksm_image_tag: v1.0.1
k8s_prometheus_nodeexport_image: prom/node-exporter
k8s_prometheus_nodeexport_image_tag: v0.14.0
k8s_prometheus_pushgateway_image: prom/pushgateway
k8s_prometheus_pushgateway_image_tag: v0.4.0
k8s_prometheus_grafana_image: grafana/grafana
k8s_prometheus_grafana_image_tag: 4.5.2

# Prometheus additional images
k8s_prometheus_configreload_image: jimmidyson/configmap-reload
k8s_prometheus_configreload_image_tag: v0.1

# Prometheus alert configs for Slack
prometheus_slack_api_url: ''
prometheus_slack_channel: ''

