---
# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_addons_dir: '{{ k8s_conf_dir }}/addons'

# Master hosts nsmes
k8s_master_hosts: {}

k8s_prometheus_name: ''
k8s_prometheus_alertmanager_name: ''
k8s_prometheus_pushgateway_name: ''

k8s_prometheus_image: prom/prometheus
k8s_prometheus_image_tag: v1.5.1
k8s_prometheus_alertmanager_image: prom/alertmanager
k8s_prometheus_alertmanager_image_tag: v0.5.1
k8s_prometheus_configreload_image: jimmidyson/configmap-reload
k8s_prometheus_configreload_image_tag: v0.1
k8s_prometheus_ksm_image: gcr.io/google_containers/kube-state-metrics
k8s_prometheus_ksm_image_tag: v0.4.1
k8s_prometheus_nodeexport_image: prom/node-exporter
k8s_prometheus_nodeexport_image_tag: v0.13.0
k8s_prometheus_pushgateway_image: prom/pushgateway
k8s_prometheus_pushgateway_image_tag: v0.4.0

prometheus_slack_api_url: ''
prometheus_slack_channel: ''

