---
# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_prometheus_dir: '{{ k8s_conf_dir }}/addons/prometheus'

# Master hosts names
k8s_master_hosts: {}

# Prometheus host names (for Prometheus, AlertManager, PushGateway, Grafana)
k8s_prometheus_name: ''
k8s_prometheus_alertmanager_name: ''
k8s_prometheus_pushgateway_name: ''
k8s_prometheus_grafana_name: ''
k8s_prometheus_blackbox_name: ''

# Prometheus namespace
k8s_prometheus_namespace: prometheus

# Prometheus images
k8s_prometheus_image: prom/prometheus
k8s_prometheus_image_tag: v2.0.0-rc.1
k8s_prometheus_alertmanager_image: prom/alertmanager
k8s_prometheus_alertmanager_image_tag: v0.9.1
k8s_prometheus_ksm_image: gcr.io/google_containers/kube-state-metrics
k8s_prometheus_ksm_image_tag: v0.5.0
k8s_prometheus_nodeexport_image: prom/node-exporter
k8s_prometheus_nodeexport_image_tag: v0.15.0
k8s_prometheus_pushgateway_image: prom/pushgateway
k8s_prometheus_pushgateway_image_tag: v0.4.0
k8s_prometheus_grafana_image: grafana/grafana
k8s_prometheus_grafana_image_tag: 4.5.2
k8s_prometheus_grafana_watcher_image: quay.io/coreos/grafana-watcher
k8s_prometheus_grafana_watcher_image_tag: v0.0.8

k8s_prometheus_blackbox_image: prom/blackbox-exporter
k8s_prometheus_blackbox_image_tag: v0.10.0

# Prometheus additional images
k8s_prometheus_configreload_image: jimmidyson/configmap-reload
k8s_prometheus_configreload_image_tag: v0.1

# Prometheus scrape configs
k8s_prometheus_scrape_istio_metrics: false

# Prometheus alert configs for Slack
k8s_prometheus_slack_api_url: ''
k8s_prometheus_slack_channel: ''
k8s_prometheus_slack_message_title: '{% raw %}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]{{.CommonAnnotations.summary}}{% endraw %}'
# be careful with tabs - it can break structure of yml file
k8s_prometheus_slack_message_body: |
  {% raw %}{{ range .Alerts }}
                  *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                    *Description:* {{ .Annotations.description }}
                    *Details*:
                      {{ range .Labels.SortedPairs }} • {{ .Name }}: `{{ .Value }}`
                      {{ end }}
                    {{ end }}{% endraw %}
