---
# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_addons_dir: '{{ k8s_conf_dir }}/addons'

# Master hosts nsmes
k8s_master_hosts: {}

# Prometheus image configs
k8s_prometheus_image: quay.io/coreos/prometheus
k8s_prometheus_image_tag: 1.0.2