apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-3.1.0
    component: "alertmanager"
    heritage: Tiller
    release: my-release
  name: my-release-prometheus-alertmanager
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    app: prometheus
    component: "alertmanager"
    release: my-release
  type: "ClusterIP"