apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"

  labels:
    app: prometheus
    chart: prometheus-3.1.0
    component: "kube-state-metrics"
    heritage: Tiller
    release: my-release
  name: my-release-prometheus-kube-state-metrics
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
    component: "kube-state-metrics"
    release: my-release
  type: "ClusterIP"
